[package]
name = "get_input"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.24", features = [ "blocking", "cookies" ] }
serde = { version = "1.0.228", features = [ "derive" ] }
toml = "0.9.8"
